<?php

namespace CryptYO\HomeBundle\Entity;

/**
 * RelationUserMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationUserMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
